config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

   
  resources :distances 
 
  

end

app/models/distance.rb
class Distance < ActiveRecord::Base
  #belongs_to :runner
end

app/models/runner.rb
class Runner < ActiveRecord::Base
	has_many :distances, dependent: :destroy

  def full_name
    return "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController
  def index
    @distances = Distance.all
  end 

  def show
    @distance = Distance.find(params[:id])
  end

  def new
    @distance = Distance.new
  end

  def create
    @distance = Distance.create(distance_params)
    if @distance.save
      redirect_to @distance
    else
      render :new
    end
  end

  def edit
    @distance = Distance.find(params[:id])
  end

  def update
    @distance = Distance.find(params[:id])
    
    if @distance.update(distance_params)
      redirect_to @distance
    else
      render :edit
    end
  end

  def destroy
    @distance = Distance.find(params[:id])
    @distance.destroy
    redirect_to distances_path
  end

private

  def distance_params
    params.require(:distance).permit(:date, :time)
  end
end

app/controllers/runners_controller.rb
class RunnersController < ActionController::Base
	before_action :find_runner, except: [:index, :new, :create]

  #def index
  #  @runners = Runner.all.order(:first_name)
  #end

  def new
    @runner = Runner.new
  end

  def create
    @runner = Runner.new(runner_params)
    if @runner.save
      redirect_to @runner
    end
  end

  def show
    @runners = @runner.distances.order(:time)
  end

  def edit
    @runner = Runner.find(params[:id])
  end

  def update
    if @runner.update_attributes(runner_params)
      redirect_to @runner
    end
  end

  def destroy
    if @runner.destroy
      redirect_to runners_path
    end
  end

  private

  def find_runner
    @runner = Runner.find(params[:id])
  end

  def runner_params
    params.require(:runner).permit(:first_name, :last_name, :date)
  end
end
  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/distances/edit.html.erb
<h1>Edit <%= @distance.time %></h1>

 <%= form_for @distance do |f| %>
    <%= f.label :date %>
    <%= f.text_field :date %>



	<%= f.label :time %>
    <%= f.text_field :time %>


    <%= f.submit %>
 <% end %>

app/views/distances/index.html.erb
<h1>Distances</h1>

 <ul>
 <% @distances.each do |distance| %>
   <li><%= link_to "Date: #{distance.date}, Time: #{distance.time}", distance_path(distance) %></li>
 <% end %>
 </ul>

 <%= link_to 'Add a Distance', new_distance_path %>

app/views/distances/new.html.erb
<h1>Add a Distance</h1>


<%= form_for @distance do |f| %>
    <%= f.label :date %>
    <%= f.text_field :date %>

	<%= f.label :time %>
    <%= f.text_field :time %>


    <%= f.submit %>
 <% end %>

app/views/distances/show.html.erb
<p><%= link_to "Distances", distances_path %> / <%= @distance.time %></p>  
 <h1><%= @distance.time %></h1>
 <h2><%=@distance.date %></h2>
 <p><%= link_to 'Edit', edit_distance_path(@distance) %></p>
 <%= form_for @distance, :method => :delete do |f| %>
  <%= f.submit 'Destroy' %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RungirlApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>